apiVersion: apps/v1
kind: Deployment
metadata:
  name: team8-deployment
  labels:
    app: team8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team8
  template:
    metadata:
      labels:
        app: team8
    spec:
      containers:
      - name: team8
        image: jjbasile/team8
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "2"
          limits:
            memory: "1000Mi"
            cpu: "2"